modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://github.com/AmaranthineMona/Forge-HomewardBone/issues" #optional
[[mods]] #mandatory
modId="homeward" #mandatory
version="1.0.0" #mandatory
displayName="Homeward" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://github.com/AmaranthineMona/Fabric-HomewardBone" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This mod adds a bonfire block and associated homeward bone item to allow players to quickly return home without the use of console commands or dying. Like dark souls, once a bonfire is lit a player must "rest" (right click) to pair with that bonfire. Using a homeward bone when paired with a bonfire will return the player to that location, assuming the bonfire is still present. You can only have one bonfire paired at a time, so *teleports are one way*!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.homeward]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.homeward]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
